### PR TITLE
Update the URL for the JPL rover

### PR DESCRIPTION
**Pull request by madhephaestus**
the old link is dead, the project URL has moved.

### CODE REVIEW

**Comment by Roger-random** [comment]
Who owns this domain? The now-dead link was clearly controlled by NASA but this one is unclear. 

A WHOIS query returned only information for an identity protection service. Pretty common these days, but inconclusive about ownership. https://www.whois.com/whois/jplopensourcerover.com

Given the fact this site is now outdated anyway (rover has 3D mesh reflecting V1 design, etc.) maybe it's better to point to GitHub repository instead? https://github.com/nasa-jpl/open-source-rover

**Comment by hernancurras** [comment]
@Roger-random use Github definitely... then you can spend a few bucks on a new domain...

**Comment by madhephaestus** [comment]
I updated it to the github link

**Comment by Roger-random** [comment]
Fantastic, thank you!

**Pull request merged**
